[project]
name = "dyndns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography==43.0.1",
    "requests==2.32.3",
]
